version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
  - dependency-name: "@material-ui/core"
    versions:
    - 4.11.3
  - dependency-name: react-chartjs-2
    versions:
    - 2.11.1
